_wandb:
    value:
        cli_version: 0.22.2
        e:
            9afmvcggxemld6fyebs7go4smzwe1h0l:
                codePath: class/class 7/mlops_wandb_monitoring_lab.ipynb
                codePathLocal: mlops_wandb_monitoring_lab.ipynb
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "102611623936"
                        used: "39066300416"
                email: 142502006@smail.iitpkd.ac.in
                executable: /usr/bin/python3
                git:
                    commit: c4c7a88fc0146020a0347ddf2d05a0ff7323c277
                    remote: git@github.com:Aryan123661/mlops2025w_142502006.git
                host: aryan
                memory:
                    total: "14506872832"
                os: Linux-6.8.0-85-generic-x86_64-with-glibc2.35
                program: mlops_wandb_monitoring_lab.ipynb
                python: CPython 3.10.12
                root: /media/aryan/Storage/mlops2025w_142502006/class/class 7
                startedAt: "2025-10-28T04:30:13.915641Z"
                writerId: 9afmvcggxemld6fyebs7go4smzwe1h0l
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 13
            "4": 3.10.12
            "5": 0.22.2
            "8":
                - 1
            "10":
                - 20
            "12": 0.22.2
            "13": linux-x86_64
n_estimators:
    value: 50
random_state:
    value: 42
